### PR TITLE
Adding add-remove-tag-shopify-customer-with-recharge-purchase templates

### PR DESCRIPTION
**Pull request by amandahom**
#### PR Review Checklist

Instructions:
**Add a tag to Shopify customer when customer purchases specific ReCharge subscription** template:
- Change the name of the subscription product's title in the Filter Step.
- Change the name of the tag in the Shopify Update Customer Action to the preferred tag name (do not adjust the token next to the "Recharge Tag.".

**Remove tag from Shopify customer when customer cancels ReCharge subscription** template:
- Change the name of the tag in the Filter Step. 
- Change the name of the tag in the Shopify Update Customer Action to the preferred tag name (replace the words in the first set of quotes. For example: replace: 'Subscription Created', '' . 

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [x] Key: does it include `shoppad/mesa-templates`, are the subfolders correct?
- [x] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [x] Source: lowercase
- [x] Destination: lowercase
- [x] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [x] Is code readable and well-commented?

QA
- [x] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by amandahom** [comment]
You can use the dev-mesa store for testing.
Collab: https://partners.shopify.com/111585/stores/8074199117

1. When I first tested the workflow, I created a new product in the Shopify store and added that product to the Ruleset - Products.
Screen Shot 2021-03-10 at 1 57 35 PM

2. Then, disable the other active workflows in Mesa that involved Shopify Order Creation so it doesn't trigger other workflows.
3. Place order on store using ReCharge. You can use the Credit Card number: 424242 blah whatever is shown at checkout. The date and code can be random.

To cancel the Subscription, you will need to click on the customer and find the subscription.

**Comment by anhdungpham** [comment]
Thanks for the detailed steps! They were very helpful.

**Add a tag to Shopify customer when customer purchases specific ReCharge subscription** template:
1. On the last Shopify Update Customer action, I didn't see the "Recharge" tag getting added to my customer page. I did see "Active Subscriber" which I assume is coming from Recharge.

Screen Shot 2021-03-10 at 3 08 00 PM

Is there a way to make the "Recharge" tag appear?

**Remove tag from Shopify customer when customer cancels ReCharge subscription** template:
This one worked great! :)

**Comment by amandahom** [comment]
@anhdungpham Thanks for testing! Could you show me which task(s) Mesa ran for your testing? I am not seeing a Successful: Out: Shopify Update Customer Step in the logs when you tested. I **think** I only see tasks running until it hit the Filter. 

I just placed an order again and I am seeing the Recharge Tag. You might need to update the Filter? Should have mentioned that as well. 🤦🏻‍♀️

**Comment by anhdungpham** [comment]
@amandahom You can search for my tasks using the workflow title:

Screen Shot 2021-03-11 at 2 09 59 PM

Then change the date filter to yesterday:
Screen Shot 2021-03-11 at 2 10 02 PM

Here is the link to one of my tests: https://dev-mesa.myshopify.com/admin/apps/mesa/apps/mesa/admin/shopify/queue/task/60494f73b265e37bbf286d79

I saw this error message:
Screen Shot 2021-03-11 at 2 08 53 PM

Did I make a mistake when changing the filter step?

**Pull request merged**
