### PR TITLE
Mesa: Template wizard (initial workflows)

### PR DESCRIPTION
**Pull request by jlyon**
#### PR Review Checklist

Workflows to test https://github.com/shoppad/ShopPad/pull/8661

mesa.json
- [ ] Key: Use the slug provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Name: Use the name provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Enabled: Set to `false`.
- [ ] Logging: Set to `true`.
- [ ] Debug: Set to `false`.
- [ ] Do the Input/Output names make sense? How about the keys?

Template code (Custom Code, Transform)
- [ ] Is code readable and well-commented?

QA
- [ ] Does the template work
#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by aschmoe** [comment]
- [ ] Typo 
Screenshot 2023-04-14 at 2 32 16 PM

**Comment by aschmoe** [comment]
- [ ] Missing?
  Screenshot 2023-04-14 at 2 37 27 PM

**Comment by aschmoe** [comment]
- [ ] Swap token
  Screenshot 2023-04-14 at 2 46 05 PM

**Comment by jlyon** [comment]
> "Who should receive this email?" default

I removed the default from this field since our new consensus is that the store email address isn't useful and removed the shop lookup step.  If we do want to use this value, I think it should be `{{context.shop.email}}`, but we should probably figure out a way to make the `context.shop` variables selectable in the variable selector (or at least appear as a badge).

> Add free product:  "Select the variant of the ..." description

I think the issue here is in the way we're parsing {{template}} tags with commas in their values. I'll need to look into this more tomorrow:
Screenshot 2023-04-17 at 5 24 23 PM

**Comment by jlyon** [comment]
> Add free product: "Select the variant of the ..." description

I resolved this with a commit to the main branch: https://github.com/shoppad/ShopPad/pull/8661/commits/b549196b2759fad4d6fe05ac30db6557e82b926d

**Pull request merged**
