### PR TITLE
Create new version of shopify/order/add_line_item_properties_to_notes

### PR DESCRIPTION
**Pull request by jlyon**
#### PR Review Checklist
Requires Mesa Core PR: https://github.com/shoppad/ShopPad/pull/7400

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [ ] Key: does it reflect the folder structure? For instance, if the folder for the template is `shopify/order/send_to_another_system`, the key should be the same. 
- [ ] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [ ] Source: lowercase
- [ ] Destination: lowercase
- [ ] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [ ] Is code readable and well-commented?

QA
- [x] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by anhdungpham** [comment]
@jlyon This works great! 🥳

One minor thing I did noticed:
Screen Shot 2021-10-05 at 9 20 14 AM

The two bottom {% endfor %} display on the same line. Could we please have each {% endfor %} display on their own line?

**Comment by jlyon** [comment]
@anhdungpham I needed to combine some of these liquid tags on the same line to prevent a bunch of weird line breaks in the Note Attributes.  I think when I had the ` {% endfor %}`s on separate lines there were two line breaks between each product.  I know it's annoying and not the most readable, but I think the end output is probably the most important. What do you think?

**Comment by anhdungpham** [comment]
@jlyon I agree with the end output being the most important. It shouldn't be a huge deal if they are on the same line.

**Comment by jlyon** [comment]
@anhdungpham do you think we should have any default readme for this template, or should we use it as a test-case for the new Helpscout doc/beacon flow?

**Comment by anhdungpham** [comment]
@jlyon Since the adjustments happen mainly on the Shopify Update Order action, I think it should be a test-case for the new Helpscout doc/beacon flow.

**Pull request merged**
