### PR TITLE
Update IO/Uploadery sheets templates to auto-create docs; iterator to loop updates

### PR DESCRIPTION
**Pull request by jlyon**
#### PR Review Checklist

- [x] Update install instruction docs
- [x] Test workflows

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [ ] Key: does it reflect the folder structure? For instance, if the folder for the template is `shopify/order/send_to_another_system`, the key should be the same. 
- [ ] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [ ] Source: lowercase
- [ ] Destination: lowercase
- [ ] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [ ] Is code readable and well-commented?

QA
- [ ] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by anhdungpham** [comment]
@jlyon The Airtable template worked great, however I noticed two issues with the Google Sheets ones:

1. "Add Infinite Options Line Items to Google Sheet"

The Google Sheets Create Row sheet isn't displaying properly.

Screen Shot 2021-12-13 at 10 21 39 AM

2. "Add Uploadery Line Items to Google Sheet"

When clicking the "Update spreadsheet columns" button, the columns in the Mesa workflow did not update.

Screen Shot 2021-12-13 at 10 25 39 AM

Screen Shot 2021-12-13 at 10 25 46 AM

Could you please take another look?

**Comment by jlyon** [comment]
@anhdungpham I fixed the issue with the IO template's step not appearing properly.

> When clicking the "Update spreadsheet columns" button, the columns in the Mesa workflow did not update.

This one I couldn't replicate in either the IO or Uploadery templates.

Could you take another look? Thanks!

**Comment by anhdungpham** [comment]
@jlyon Thanks for making the changes! The IO template's Google Sheets Add Row is displaying correctly.

The issue seems to occur after updating the spreadsheet's title and sheet name. Could you please try updating the title and sheet name, then adding new column headers, and then clicking the "Update spreadsheet columns" button?

**Comment by jlyon** [comment]
@anhdungpham It looks like there's an issue when you change the sheet name (Say from `Sheet1` to `Test`:
- If you remove the Sheet, and then re-select the sheet, if will properly sync
- However, if you just refresh your workflow, the Sheet value in the UI will update to your new value (`Test`), but the value stored in the database (and used for all Mesa functionality) will remain `Sheet1`.
Expected behavior: 
A) The Sheet value in the UI should remain `Sheet1` so that you know you need to select a new sheet (more explicit)
B) OR The Sheet value should automatically update to `Test` everywhere (probably makes the most sense in 99% of cases)

**Comment by anhdungpham** [comment]
@jlyon I would go for Option B since it does make the most sense.

**Comment by jlyon** [comment]
@anhdungpham I ended up opting against automatically updating the Sheet Name in Mesa because there were too many opportunities for that logic to break down.

Now, if you change the sheet name in Google Sheets, Mesa will:
- Leave the old Sheet Name as the value in the Sheet Name field
- If you click Update spreadsheet columns, an error will appear, saying that we couldn't find the sheet name
- If you wipe out your Sheet name value, the new sheet name will appear. Select it
- When you click the Update spreadsheet columns button, column headers will be added to your new sheet if necessary

**Comment by anhdungpham** [comment]
@jlyon Thanks for the details! The changes look good. I did noticed one odd thing.

For the "Add Uploadery Line Items to Google Sheet" template, I noticed that these 5 columns weren't filling in when using a test payload.
Screen Shot 2021-12-22 at 10 11 06 AM

I checked the payload and it looks like there is a wrapping 'order' object name.
Screen Shot 2021-12-22 at 10 12 16 AM

So I updated one of the Tokens `{{uploadery_order_created.order.order.shipping_address.name}}` and it showed up.

Could we please remove the wrapping 'order' object name?

**Comment by anhdungpham** [comment]
@jlyon QA'd and works great! 🥳

**Pull request merged**
