### PR TITLE
Recharge: Tagging customer when subscription it's created updates

### PR DESCRIPTION
**Pull request by itsdarrylnorris**
#### PR Review Checklist

Test out the following themplates
- Remove a Shopify customer tag when a Recharge subscription product is canceled
- Tag a customer when a subscription is purchased

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [ ] Key: does it reflect the folder structure? For instance, if the folder for the template is `shopify/order/send_to_another_system`, the key should be the same. 
- [ ] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [ ] Source: lowercase
- [ ] Destination: lowercase
- [ ] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [ ] Is code readable and well-commented?

QA
- [ ] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by amandahom** [comment]
As mentioned in my Slacks, I couldn't activate the Subscription Created Trigger. I think we mean Order Created Trigger. Since the adding tag template didnt activate, I couldn't test the remove tag template. 

I also recommend using the updated Shopify actions that remove or add tags specifically.

**Comment by amandahom** [comment]
Okay okay, my thoughts:
1. Adding tag template works but we can improve the template with the Shopify Customer Add Tag Action. 
2. The remove tag template relies on the add tag template (needs the "Recharge Tag"). Shouldn't we mention this in the template descriptions?
3. The Add tag template has a Filter but is that really necessary? Cant we just remove the Filter?
4. The Remove tag template needs to be updated with the correct token. I had an error but got it fixed by changing the token in the Shopify Retrieve Customer Step.
Screen Shot 2022-03-01 at 11 28 56 AM
5. We can improve the remove tag template with the Shopify Customer Remove Tag Action.

**Comment by itsdarrylnorris** [comment]
> 1. Adding tag template works but we can improve the template with the Shopify Customer Add Tag Action.

Done

> 2. The remove tag template relies on the add tag template (needs the "Recharge Tag"). Shouldn't we mention this in the template descriptions?

I will let Jen know and she can update it accordingly if needed it.

> 3. The Add tag template has a Filter but is that really necessary? Cant we just remove the Filter?

I do not think it's necessary, I remove the filter.

> 4. The Remove tag template needs to be updated with the correct token. I had an error but got it fixed by changing the token in the Shopify Retrieve Customer Step.

Thanks, I have updated this in the PR.

> 5. We can improve the remove tag template with the Shopify Customer Remove Tag Action.

Done


Hey @amandahom Can you qa the templates again? Thanks

**Comment by amandahom** [comment]
Tested and the 2 templates work great now :)

**Pull request merged**
