### PR TITLE
HubSpot: v3 template updates

### PR DESCRIPTION
**Pull request by marinerjohn**
Update templates to reflect Hubspot v3 updates in https://github.com/shoppad/ShopPad/pull/7868

See https://app.asana.com/0/1199933048569373/1202242239820025

#### PR Review Checklist

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [ ] Key: does it reflect the folder structure? For instance, if the folder for the template is `shopify/order/send_to_another_system`, the key should be the same. 
- [ ] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [ ] Source: lowercase
- [ ] Destination: lowercase
- [ ] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [ ] Is code readable and well-commented?

QA
Check these templates work, and update docs for them
- [ ] Send Draft Order To HubSpot Deal (code done)
- [ ] Send Order To HubSpot Deal (code done)
- [ ] Send Shopify Customer to HubSpot Contact and Deal (code done)
- [ ] Send Shopify Customer To HubSpot Contact And Mark As Opportunity (code done)
- [ ] Send Shopify Customer To HubSpot Contact (code done)
- [ ] Send HubSpot Contact To Shopify Customer  (code done)

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by anhdungpham** [comment]
@marinerjohn I took a first look and provided a list of what I noticed below.

**All templates**
- [ ] Could you please set `logging` to `true` on all templates?

**Send Draft Order To HubSpot Deal**
- [ ] In the **HubSpot Create Deal** step after creating a credential, the values for Pipeline (i.e. Sales Pipeline), Deal Stage (i.e. Appointment Scheduled), and Hubspot Owner ID (i.e. Mesa Saas) fields sometimes do not show. It seems to occur more often before saving changes. Could you please fix this?

    Please see my Loom video: https://www.loom.com/share/e701be77c27947169302412e657315f1

- [ ] Errors occurs when I set the **Close Date** field for both Date picker and Token Selector options. Could you please fix this?

    Run using Close Date's Date picker: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-ahn-2/mesa/automations/6282b785ffe29423920b5830/queue/task/6282b91cc1e7c85590746489

    Run using Close Date's Token Selector: 
https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-ahn-2/mesa/automations/6282b785ffe29423920b5830/queue/task/6282b95029a8e476f00b28bd

Screen Shot 2022-05-16 at 2 44 34 PM

- [ ] Is there a way to un-select the date via Date picker? I didn't see a way.

**Send Order To HubSpot Deal**
- [ ] I am unable to install the template. I see this error message in my image below. Could you please fix installing the template?
Screen Shot 2022-05-16 at 2 47 28 PM

**Send Shopify Customer to HubSpot Contact and Deal**
- [ ] Same issue as the **Send Draft Order to Hubspot Deal** template regarding values for Pipeline, Deal Stage, and Hubspot Owner ID fields.
- [ ] Same error as the **Send Draft Order to Hubspot Deal** template when setting **Close Date** field for both Date picker and Token Selector options.

**Send Shopify Customer To HubSpot Contact And Mark As Opportunity**
This one worked great! 🥳

**Send Shopify Customer To HubSpot Contact**
This one worked great! 2 for 2! 🥳

**Send HubSpot Contact To Shopify Customer**
- [ ] HubSpot Contact Updated trigger's polling input shows "Workflow disabled" when the workflow is enabled. Could you please fix this so it displays the time for the next run?
Screen Shot 2022-05-16 at 3 23 20 PM

Despite the one issue, the one runs great! 3 for 3! 🥳

**Comment by marinerjohn** [comment]
@anhdungpham just reviewed the feedback, couple of things to discuss:

`Errors occurs when I set the Close Date field for both Date picker and Token Selector options. Could you please fix this?`
- Yep so this field only expects a date, not date time. But HubSpot's API doesn't document this. I will have to add special handling which will remove the time portion for this field. 

` Is there a way to un-select the date via Date picker? I didn't see a way.`
- Good shout. This is actually an issue generally with the Date / Date Time picker, across all connectors. I've created an Asana issue, which warrants some discussion: https://app.asana.com/0/393037162945950/1202294210516970

**Comment by anhdungpham** [comment]
@marinerjohn 
**Send Draft Order To HubSpot Deal**
I am no longer seeing errors when selecting a Close Date via Date Picker or Token Selector. Yay!

- [ ] For the Date picker, I noticed that the Close Date added to HubSpot is one day before I selected. I selected May 19, 2022, but it showed up as May 18, 2022 on HubSpot. Could we please fix this so that the Close Date matches on HubSpot?
Screen Shot 2022-05-18 at 11 27 48 AM
Screen Shot 2022-05-18 at 11 28 36 AM

    Workflow run: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-ahn-2/mesa/automations/62853818bcbd26736971d301/queue/task/628538f30080382d4f43fbe2
    HubSpot Deal: https://app.hubspot.com/contacts/20117122/deal/8947706784/

- [ ] For the Token selector, I used the Draft Order Created At token`{{shopify_draft_order.created_at}}` and created a draft order today. This is having the same issue where the Close Date on HubSpot displays one day before. (i.e. 05/17/2022). Could we please fix this so that the Close Date matches on HubSpot?

    Workflow run: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-ahn-2/mesa/automations/62853818bcbd26736971d301/queue/task/62853a131dd1af036e59d5df
    HubSpot Deal: https://app.hubspot.com/contacts/20117122/deal/8947718542/

**Send Order To HubSpot Deal**
I am able to install this template and run it successfully! Yay! 

However, I did noticed a similar behavior like the **Send Draft Order To HubSpot Deal** template above.

- [ ] Close Date not matching on HubSpot via Date Picker
- [ ] Close Date not matching on HubSpot via Token Selector (i.e.  Order Created At token `{{shopify_order.created_at}}`)

**Send HubSpot Contact To Shopify Customer**
I am seeing the time for the next run displaying after enabling the workflow. Yay!

- [ ] One minor thing: When I select **Weekly** and there is no selection of the day, I see this error message when I save the workflow. Should we have a day selected by default?
Screen Shot 2022-05-18 at 11 43 05 AM

**Comment by marinerjohn** [comment]
@anhdungpham all close date related issues have been fixed. https://github.com/shoppad/ShopPad/pull/8075

HubSpot needs the dates to be sent in UTC format, I have made changes to make this happen. Please re-test when you get a chance!

As for Scheduler, that's a great shout. Another one which affects all triggers with this input, so I would raise an Asana task.

**Comment by anhdungpham** [comment]
@marinerjohn 

**Send Draft Order To HubSpot Deal**
This one works great! 🥳

**Send Order To HubSpot Deal**
This one also works great!

**Pull request merged**
