### PR TITLE
Add template: Create an order fulfillment from a new row in Google Sheets

### PR DESCRIPTION
**Pull request by anhdungpham**
#### Description
- Asana: [Create a Shopify order fulfillment from a new row in Google Sheets](https://app.asana.com/0/1199933048569373/1205863970962585/f)

#### QA Checklist
- [x] Import to MESA dashboard via the file `google_sheets/row/create_fulfillment_from_new_row/mesa.json`
- [ ] Go through the Template Setup. Do the questions ask make sense?
- [ ] View the 'Builder' tab. Expand the `Row Created' step.
- [x] Change the frequency to something sooner (i.e. 'Every 5 minutes') so you do not need to wait long
- [ ] Click 'Save changes' to save your changes
- [x] Check the Google Sheets spreadsheet that was created. Check that it has the 3 column headers (i.e. 'Order Name (Number)', 'Tracking Company', and 'Tracking Number')
- [ ] Go back to the MESA dashboard. Turn on 'Debug Logs' and turn on the workflow
- [ ] In Shopify Admin, create an unfulfilled order from your storefront
- [ ] Locate a tracking number you could use to fulfill the order
- [x] In Google Sheets, fill in a row. You can see the example screenshot below as a guide
- [ ] Wait till the frequency will trigger for the MESA workflow
- [ ] Go back to the MESA dashboard. Check that the workflow ran successfully
- [ ] Check that the messages in the Logs page make sense
- [ ] In Shopify Admin, check that the order was fulfilled by MESA
- [ ] Does the template work

Screenshot 2024-07-01 at 12 01 37 PM

#### PR Review Checklist

mesa.json
- [ ] key: Use the slug provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] name: Use the name provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] version: Keep as is.
- [ ] description: Remove this since we rely on Prismic.
- [ ] seconds: Remove this since we rely on Prismic.
- [ ] enabled: Set to `false`
- [ ] setup: Set to `true` to add the template setup. Otherwise, keep `false` if template setup is not applicable. For Google Sheets templates, set to `custom` as mentioned in the [Authoring templates that support the setup wizard](https://github.com/shoppad/ShopPad/blob/master/pub-site/apps/mesa/docs/authoring-templates.md#custom-template-setup-fields) documentation.
- [ ] Do the Input/Output names make sense? How about the keys?

Template code (Custom Code, Transform)
- [ ] Is code readable and well-commented?

#### Deploy Checklist
- [ ] Squash and merge PR

#### Post-Deploy Checklist
- [ ] [Publish Prismic draft](https://mesa.prismic.io/builder/pages/ZoL7dxEAACEAZPFO?s=unclassified&fallback=YiUzRHdvcmtpbmclMjZjJTNEdW5jbGFzc2lmaWVkJTI2bCUzRGVuLXVz)

### CODE REVIEW

**Comment by amandahom** [comment]
@anhdungpham 
- [ ] I think the question `What is your store's location of the order fulfillment?` is kinda confusing. Maybe `What location would you like to create an order fulfillment with?`?
- [ ] Maybe add some details that the product must be available at the location as well?
- [ ] I recommend improving the Get List of Orders to search for order name. It's a hidden parameter. That way, I don't get a list of 250 orders. I think you can do something like `name={ }`
- [ ] I can continue QA'ing after the parameter change^ since I have a ton of orders and I don't wanna loop over 250 on a testing store.

**Comment by anhdungpham** [comment]
@amandahom 
Thanks for the feedback! I made adjustments based on your suggestions.

Could you please pull the latest changes and QA again?

**Comment by amandahom** [comment]
@anhdungpham Thanks for adding the name parameter. I got an error at the Create Order Fulfillment step because I accidentally ran a test on an order that was fulfilled. It looks like we need to add one more parameter, `fulfillment_status
`, to the **Get Unfulfilled Order** step.
Screenshot 2024-07-03 at 10 49 33 AM

**Comment by anhdungpham** [comment]
@amandahom 
Updated. Could you please pull the latest changes again and test?

**Pull request merged**
