### PR TITLE
Add template: Email a discount code when a Google Forms response is received

### PR DESCRIPTION
**Pull request by anhdungpham**
#### Description
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205495450502956/f)

#### QA Checklist
- [ ] Go to the Shopify Admin
- [ ] Go to Discounts
- [ ] Create a new discount code that takes off a percentage value. (https://help.shopify.com/en/manual/discounts/discount-types/percentage-fixed-amount)
- [ ] Save changes
- [ ] Go to MESA
- [ ] Compress these files together and import the workflow template
    - `googleforms/response/email_discount_code_when_form_is_completed/custom.js`
    - `googleforms/response/email_discount_code_when_form_is_completed/mesa.json`
- [x] Start the Template Setup
- [ ] On the "Install the webhook code" page, click Documentation
- [x] Follow the documentation to install the webhook code. While creating your Google Form, make sure to include an "Email" field
- [x] Select the discount code you created
- [ ] Complete the Template Setup. Skip running a test
- [ ] Turn on workflow, Logging, and Logging debug mode
- [x] Save changes
- [x] In the Builder tab, view the Email Send Email step. Read what is filled in there
- [ ] Test the workflow following the directions in this guide (https://docs.getmesa.com/article/1795-google-forms#test). While filling out your Google Form, make sure to use your email
- [ ] Check that the workflow ran successfully. Check the Logs page
- [ ] Check that you received an email in your email client. Check that the contents make sense
- [ ] Test using your discount code by creating an order on your storefront and using the discount code in the checkout page
- [x] Does the template work

#### PR Review Checklist

mesa.json
- [ ] key: Use the slug provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] name: Use the name provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] version: Keep as is.
- [ ] description: Remove this since we rely on Prismic.
- [ ] seconds: Remove this since we rely on Prismic.
- [ ] enabled: Set to `false`
- [ ] setup: Set to `true` to add the template setup. Otherwise, keep `false` if template setup is not applicable. For Google Sheets templates, set to `custom` as mentioned in the [Authoring templates that support the setup wizard](https://github.com/shoppad/ShopPad/blob/master/pub-site/apps/mesa/docs/authoring-templates.md#custom-template-setup-fields) documentation.
- [ ] Do the Input/Output names make sense? How about the keys?

Template code (Custom Code, Transform)
- [ ] Is code readable and well-commented?

#### Deploy Checklist
- [ ] Squash and merge PR

### CODE REVIEW

**Comment by amandahom** [comment]
@anhdungpham Hey. While testing, I received errors for:
- https://www.theshoppad.com/homeroom.theshoppad.com/admin/supertool/shoppad-amanda/mesa/automations/6594a1eec143353ed559b229/queue/task/6594a2e65e579427197b0967
- https://www.theshoppad.com/homeroom.theshoppad.com/admin/supertool/shoppad-amanda/mesa/automations/6594a1eec143353ed559b229/queue/task/6594a3a6e44c817c956a25d9

I would recommend adding a Filter that checks for an email address and {{shopify.0.price_rule_id}} variable. Do we plan to mention that the merchant must have a form with email address anywhere?

- [ ] I can't seem to create a Google Form with an email address field and get an email address in the payload. If it was working for you, maybe ignore my inability to test the email address submission part?

Other than that, the workflow seems to work!

**Comment by anhdungpham** [comment]
@amandahom 
**(1)** Thanks for the feedback. I added a Filter step to check the email.

For adding the Filter step to check the `{{shopify.0.price_rule_id}}` variable, could you please clarify why you ran into that error `404 error: Not Found. Check that the ID sent is correct and exists and replay this step.` on the Shopify Retrieve Price Rule step? Is it cause you did not create a discount code? I just want to get a better understanding.

It seems that it would be useful if it resulted in an error there in case it is in fact that the discount wasn't set up properly.

**(2)** 
> Do we plan to mention that the merchant must have a form with email address anywhere?

I'm not sure how we would present these instructions. Probably on the description of the Google Forms' Webhook Code during the Template Setup? I shall ask Jen for thoughts after QA.

**(3)** 
>  - [ ] I can't seem to create a Google Form with an email address field and get an email address in the payload. If it was working for you, maybe ignore my inability to test the email address submission part?

There doesn't seem to be an Email Address field. A workaround would be to use the Short Answer field. Could you please try that?

Screenshot 2024-01-03 at 8 40 43 AM

**Comment by amandahom** [comment]
@anhdungpham 
1. I knew I had discount codes already so I selected one from the typeahead during the template setup: https://admin.shopify.com/store/shoppad-amanda/discounts/1164699074658
However, it looks like my random selection involved a price rule with no discount codes. It was a Mesa created price rule and I didn't realize until i ran into that error. I would think it'd be a rare case but selecting an available discount code from the typeahead made me think it was fine. So I guess adding the filter for this variable would not be helpful in this case. Perhaps it  would be better if it was mentioned during the template setup.
2. Are you referring to this email address field that Google Forms automatically adds if you have the setting enabled? https://docs.google.com/forms/d/e/1FAIpQLSeUaS7jycRxL_KBeua33ZfgwRsUY5jr-GiQupWPd_DkrdwKAQ/viewform?usp=sf_link
Screenshot 2024-01-04 at 11 57 36 AM

**Comment by anhdungpham** [comment]
@amandahom 
(1) Thanks for your thoughts. I shall mention to Jen regarding the discount code part.

(2) I wasn't. I had no idea that was a setting. After diving into some Google Forms developer documentation, I was able to determine you can get the email address from the submission. I was able to apply an update.

The update is in this PR (https://github.com/shoppad/ShopPad/pull/9641). Could you please QA that PR with this PR?

**Comment by amandahom** [comment]
@anhdungpham Both PRs work well! One last feedback item that you can ignore: I think the merchant should read or at least be aware of the email body before enabling. Just in case the email body doesn't accurately describe the discount code (e.g. if discount code applies to specific products/collections/have restrictions).

**Pull request merged**
