### PR TITLE
Updating Shopify templates

### PR DESCRIPTION
**Pull request by amandahom**
#### PR Review Checklist
- Asana Task feedbacks or they still contained the the old Shopify Admin link
Asana Tasks:
- Tag an order when expedited shipping is selected: https://app.asana.com/0/770345770753602/1204231516499476
- Changing slugs for Add Shopify Customer to Klaviyo list when tagged with "Backorder": https://app.asana.com/0/770345770753602/1204231516499470
- Send a draft order to HubSpot Deals: https://app.asana.com/0/770345770753602/1204231514090399

mesa.json
- [ ] Key: Use the slug provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Name: Use the name provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Enabled: Set to `false`.
- [ ] Logging: Set to `true`.
- [ ] Debug: Set to `false`.
- [ ] Do the Input/Output names make sense? How about the keys?

Template code (Custom Code, Transform)
- [ ] Is code readable and well-commented?

QA
**Send a draft order to HubSpot Deals**
- [x] Install template
- [x] Create a HubSpot credential (if necessary with our **HubSpot Active Testing account** 1Password Login): https://docs.getmesa.com/article/1293-hubspot#connect
- [x] Save/Enable/Enable Logging/Enable Debug Logging
- [x] Test with a draft order that contains the following:
Customer First Name
Customer Last Name
Customer Email
- [x] If you don't have one, create a draft order with the information above
- [x] Login into our HubSpot account and locate the new deal
- [x] Does the template work & does the deal name look correct?

**Cancel high-risk orders**
- [x] Install template
- [x] Need to create an order risk in order to properly test this workflow. Add a "Shopify Create Order Risk" step after the "Order Created" Trigger:
Screen Shot 2022-04-26 at 11 21 46 AM
- [x] Fill in the Shopify Create Order  Risk fields like this:
Screen Shot 2022-04-26 at 11 20 19 AM
- [x] Save/Enable/Enable Logging/Enable Debug Logging
- [x] Run a test on a past order
- [x] Does the template work
- [x] Does the Shopify Admin link in the email work?

**Tag an order when expedited shipping is selected**
- [x] Install template
- [x] Save/Enable/Enable Logging/Enable Debug Logging
- [x] Run a test on a past order
- [x] If your automation stopped, click to continue after the Filter from the Activity tab.
- [x] Does the template work
- [x] Does the Shopify Admin link in the email work?

**Send a Slack message when a product goes out of stock**
- [x] Install template
- [x] Set up a Slack credential (if it isn't set up already): https://docs.getmesa.com/article/1229-slack#connect
- [x] Select **Channel**.
- [x] Look over the **Message** field.
- [x] Save changes.
- [x] Save/Enable/Enable Logging/Enable Debug Logging
- [x] In your Shopify admin > **Products** page, set a product's variant to have a quantity of 1.
- [x] Create a test order on your store with that product's variant.
- [x] Check that the workflow ran successfully.
- [x] Check that you received a Slack message and the message look good.
- [x] Does the template work & does the Shopify Admin link in the Slack message work?

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by anhdungpham** [comment]
@amandahom 

**Send a Slack message when a product goes out of stock**

> - [ ] Check that you received a Slack message and the message look good.

Regarding this checklist item, it looks like the `**` displays in the message if there is no SKU.

Screenshot 2023-03-27 at 2 00 25 PM

Here is my suggestion on how we could handle that. We could have a different first sentence when there is no SKU. Maybe we could use the product name + variant name instead of the SKU?

**Comment by amandahom** [comment]
@anhdungpham Thanks for letting me know. Could you please try again with a product that doesn't have a SKU and a product that does?

**Comment by anhdungpham** [comment]
@amandahom Your changes look good so far!

Maybe one more thing to take note of is when there is only one variant, since the message displays `Default Title`.

Screenshot 2023-03-27 at 3 31 36 PM

My suggestion would be checking if the variant title is not `Default Title`, then include the Variant Title.

**Comment by amandahom** [comment]
@anhdungpham No problem! Can you please try with:
- A product without sku but has a variant
- A product without sku and no variant
- A product with SKU

**Comment by anhdungpham** [comment]
@amandahom QA'd and works great! 👍🏻

**Pull request merged**
