### PR TITLE
Delighted: Add Send a Slack message when a customer gives a low Delighted survey score template

### PR DESCRIPTION
**Pull request by anhdungpham**
#### PR Review Checklist

mesa.json
- [ ] Key: Use the slug provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Name: Use the name provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Enabled: Set to `false`.
- [ ] Logging: Set to `true`.
- [ ] Debug: Set to `false`.
- [ ] Do the Input/Output names make sense? How about the keys?

Template code (Custom Code, Transform)
- [ ] Is code readable and well-commented?

QA
- [x] Log in to our **dev-mesa** store.
- [x] Go to the MESA dashboard.
- [x] Import the template.
- [x] Open the **Delighted Survey Response** trigger and set up the Webhook URL. You can follow steps 1 to 4 in this [MESA guide](https://docs.getmesa.com/article/1608-send-an-email-to-staff-when-a-low-delighted-score-is-posted).
- [x] In the **Slack Send Message** step, set up your Slack credential.
- [x] In the **Step Configuration** section, select your Slack channel.
- [x] Check the contents of the **Message** field. No need to adjust it.
- [x] Save your changes.
- [x] Enable **Logging** and **Debug Logging**.
- [x] Enable the workflow.
- [x] Go to the **Delighted** dashboard.
- [x] Click the **Survey People** button.
- [x] Click **Email**.
- [x] Fill in your name and email (like the placeholder text shows).
- [x] Click **Next: Review**.
- [x] Click **Send**.
- [x] Check your email for the Delighted survey. Subject line is "How likely are you to recommend dev-mesa to a friend?"
- [x] Open the email. 
- [x] Select a score less than 5.
- [x] Write a brief description.
- [x] Click **Submit**.
- [x] Go back to MESA.
- [x] Check that the workflow ran successfully.
- [x] Check the messages in the **Logs** tab make sense.
- [x] Go to Slack.
- [x] Check that you received a Slack message with details.
- [x] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by amandahom** [comment]
@anhdungpham I haven't received an email (been 20 mins) but I wonder if I need to be more patient. 

In the meantime, should we assume that all responses come from Email? I tested it via link and the name token makes the message a bit odd:
Screen Shot 2023-02-07 at 12 29 24 PM

**Comment by anhdungpham** [comment]
@amandahom 

1. It looks like our trial account is expired for our dev-mesa store. I can make an Asana ticket soon to see if we can request a developer account.

In the meantime, could you please try creating a new account with a trial?

2. I would assume email since that would be helpful in reaching back out to the customer. When I create the Help Scout guide, I can recommend that the survey be sent via email.

**Comment by amandahom** [comment]
@anhdungpham Sorry I didnt mention that I already created a new account. 

mandysfgiants13@gmail.com
dqg6dwq!nkf*gjx9BVG

Running out of emails to use lol

Do you wanna try or give me permission to use your email address? 

Workflow: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/dev-mesa/mesa/automations/63e2b08774fe5062e64b1612

**Comment by anhdungpham** [comment]
@amandahom No worries. I would offer my email to create a Delighted account, but I already used my trial.

In your Delighted account, it says the emails are sending. I attached a screenshot.
Screenshot 2023-02-07 at 2 38 42 PM

Let's try waiting to see if an email comes tomorrow.

**Pull request merged**
