### PR TITLE
Add template: Add a customer's Recharge order count to order notes

### PR DESCRIPTION
**Pull request by anhdungpham**
#### Description
Asana: [Add customer's Recharge order to order notes](https://app.asana.com/0/1199933048569373/1204342340814559/f)

#### QA Checklist
- [x] Log into our dev-mesa2 store
- [ ] In MESA, install the template
- [x] Go through the setup wizard
- [ ] Do the questions make sense
- [ ] Turn on Logging
- [x] Turn on Logging debug mode
- [ ] Create a Recharge order on the storefront. Make sure it is the first order of a subscription
- [ ] Check that the workflow ran successfully
- [ ] Go to your Shopify admin
- [x] Check that the order includes the note
- [x] Does the template work

#### PR Review Checklist

mesa.json
- [ ] Key: Use the slug provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Name: Use the name provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] Enabled: Set to `false`
- [ ] Logging: Set to `true`
- [ ] Debug: Set to `false`
- [ ] Do the Input/Output names make sense? How about the keys?

Template code (Custom Code, Transform)
- [ ] Is code readable and well-commented?

#### Deploy Checklist
- [ ] Squash and merge PR

### CODE REVIEW

**Comment by amandahom** [comment]
@anhdungpham I am seeing the same set-up step for both Step 1 and 2: 
Screenshot 2023-04-25 at 3 00 37 PM
Screenshot 2023-04-25 at 3 00 41 PM

I am clicking Next on Step 1 because I run into a credential error if I click on "Connect with Recharge" :(
Screenshot 2023-04-25 at 3 02 29 PM

Workflow: https://www.theshoppad.com/homeroom.theshoppad.com/admin/supertool/dev-mesa2/mesa/automations/64484d7f64a63f6399085922/setup/installed

**Comment by anhdungpham** [comment]
@amandahom 

1) The workflow has multiple Recharge steps, so it looks like it goes through both of them with the setup wizard. 

I asked Noah and he says it probably would at this time. I shall create an Asana ticket.

2) Do you have steps I can follow to replicate the credential error?

**Comment by anhdungpham** [comment]
@amandahom 

1. I imported the workflow on the dev-mesa2 store recently. I was able to see all 5 steps in the template setup wizard. I also was able to create a new Recharge credential.

I tried on an incognito window and had the same experience. Could you please try on an incognito window?

Screenshot 2023-04-26 at 7 39 27 AM
Screenshot 2023-04-26 at 7 39 51 AM
Screenshot 2023-04-26 at 7 39 55 AM
Screenshot 2023-04-26 at 7 40 09 AM

**Comment by amandahom** [comment]
@anhdungpham Sorry, I am still seeing 3 steps in total and the recharge credential step twice (no notes step). Tested this on mesa-testing in incognito: 
[recharge_order_add_order_count_to_order_notes (1).zip](https://github.com/shoppad/mesa-templates/files/11337887/recharge_order_add_order_count_to_order_notes.1.zip)

Video: https://www.loom.com/share/072adb86f9b342a9844f3db7ae86aad1

**Pull request merged**
