### PR TITLE
Adding mesa forms

### PR DESCRIPTION
**Pull request by jlyon**
#### PR Review Checklist

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [ ] Key: does it include `shoppad/mesa-templates`, are the subfolders correct?
- [ ] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [ ] Source: lowercase
- [ ] Destination: lowercase
- [ ] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [ ] Is code readable and well-commented?

QA
- [ ] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by amandahom** [comment]
**Template: Send Contact Form Submissions to Email and Slack**

1. Ran into issues with the **To email address** field in the Email Step. Had to enter my own email address to fix the error.
Screen Shot 2021-03-01 at 2 02 50 PM
2. When replaying the same first task that I filled out the form for, I had an error for the Content-Type.
Task: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-amanda/mesa/queue/task/603d64a43e280f20d84c941f/replay
Screen Shot 2021-03-01 at 2 03 32 PM
3. Typo in company in both Email and Slack Steps:
Screen Shot 2021-03-01 at 2 08 49 PM
4. Probably get rid of the Company field all together because the form does not have a company field in the Form.

**Template: Save a Customer's Date of Birth to Notes**
1. Ran into issues with updating the customer's ID. The payload does not contain the ID so an error occurs.
Not sure how to fix this since the form does not contain any information about customer's existing account? I did login into the customer account when testing.
Embedded code on a page: https://shoppad-amanda.myshopify.com/pages/test
Task: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-amanda/mesa/queue/task/603d67b67b77de6906723492/payload
Screen Shot 2021-03-01 at 2 17 10 PM

**Comment by amandahom** [comment]
**Template: Start a Return with Mesa Forms**
1. Ran into issues with the email recipient. Currently: {{shopify_customer.email}}
Should be: {{shopify_order.customer.email}}

2. Ran into issues with the customer's name. Currently: {{shopify_customer.first_name}}
Should be: {{shopify_order.customer.first_name}}

3. Ran into issues with Context.store.name. 
Screen Shot 2021-03-03 at 3 14 12 PM

**Comment by jlyon** [comment]
**Template: Send Contact Form Submissions to Email and Slack**

1. Fixed To email address (token needed to be context.shop.email, not context.store.email)
2. Error on replay: Hmm, I wasn't able to replicate this one (I was able to replay my form submission task), but I added a check to make sure that `context.headers` exists that should prevent this from happening.
3+4: I think the issue was that the company typo was in the form field, and in the tokens. I fixed it.

Pull the latest code on this `mesa-forms` branch and try re-installing the template.


** Template: Save a Customer's Date of Birth to Notes **
The automatic Customer ID only works for a Shopify embedded form, because we're using liquid code to add a hidden field to the form with the customer_id value:
```
<input type="hidden" name="shopify_customer_id" value="{{ customer.id }}" />
```
It looks like you embedded the form HTML code into a (Pagestudio?) page, which is a great way to use Mesa forms in general, but won't set the customer_id with the logged-in shopify customer account automatically.  Try submitting from https://shoppad-amanda.myshopify.com/apps/mesa/forms/form_customer_dob instead.  Lmk if you think these steps are unclear: https://github.com/shoppad/mesa-templates/blob/60d40b3e5b5b7cbd27ef217ec9ab03b6b55ce9f7/form/customer_dob/README.md#L9


**Template: Start a Return with Mesa Forms**
Thanks, I fixed these tokens. Please try re-installing the template.

**Comment by amandahom** [comment]
**Template: Send Contact Form Submissions to Email and Slack**
 - Should set the **Enable** field to **false** since we need a Slack credential. 
 - Should we include the Email field/token in the Slack message? Since it is a field that is filled out in the form. 
 
**Template: Save a Customer's Date of Birth to Notes**
- Works great. Did you plan to remove the Read.me and move that to Prismic? 

**Template: Start a Return with Mesa Forms**
- Works great. Did you plan to remove the Read.me and move that to Prismic?

**Pull request merged**
