### PR TITLE
Update templates with mapping steps

### PR DESCRIPTION
**Pull request by anhdungpham**
#### Description
Related to this Asana task: https://app.asana.com/0/562906963533984/1202379276404933

#### PR Review Checklist

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [ ] Key: does it reflect the folder structure? For instance, if the folder for the template is `shopify/order/send_to_another_system`, the key should be the same. 
- [ ] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [ ] Source: lowercase
- [ ] Destination: lowercase
- [ ] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [ ] Is code readable and well-commented?

QA
**Tag a customer if they provide a negative survey response**
- [x] Follow setup steps in HS draft: 
https://secure.helpscout.net/docs/5cba3fdc2c7d3a026fd3d8ec/article/629e45da5732000792521d7e
- [x] Use the Delighted trial account in 1PW titled "Delighted Trial Plan"
- [x] Send a survey to yourself clicking the **Survey People** button and selecting **Email**
- [x] Rate a score of less than 5 on the survey
- [x] Does the template work

**Tag customers with "VIP" after they spend $500 or more**
- [x] Enable logging, debug logging, and workflow
- [x] Create an order on your store with a customer that has spent in total more than $499.99
- [x] Does the template work

**Add customer's orders to order notes**
- [x] Enable logging, debug logging, and workflow
- [x] Create an order on your store
- [x] Check that the order has been updated with the note "Customer's `{{shopify_order.customer.orders_count}}` orders"
- [ ] Does the template work

**Flag order as risky if total price is 0**
- [x] Enable logging, debug logging, and workflow
- [x] Create an order where the total price is $0
- [x] Does the template work

**Tag an order when expedited shipping is selected**
- [x] Enable logging, debug logging, and workflow
- [x] Create an order where the shipping method is 2 days or next day
- [x] Does the template work

**Start a return with Forms by MESA**
- [x] Follow the steps in the support guide
    - [x] When you get to step 4, create a new spreadsheet on the **Google Sheets Add Row** step
- [x] Check that you receive an email and Slack message
- [x] Does the template work

**Send an updated or new Shopify Customer to a Salesforce account**
- [x] Enable logging, debug logging, and workflow
- [x] Use our dev account titled "ShopPad Salesforce sandbox"
- [x] Create or update a Shopify customer
- [x] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by amandahom** [comment]
Updating this comment as I QA:

**Add customer's orders to order notes**
- The **Shopify Update Order Notes** action is overriding or removing any existing order notes. It is always replaced with the "Customer's {{shopify_order.customer.orders_count}} orders"

**Comment by anhdungpham** [comment]
@amandahom 
- I created an [Asana ticket](https://app.asana.com/0/393037162945950/1202399657199300) to address the issue with the Shopify Update Order Notes step. 
- I switched the values in the Filter step so it reads better. Thanks for the suggestion!
- I fixed the Salesforce template so the trigger should be working now. Could you please try pulling in the new changes and test that template once more?

**Comment by amandahom** [comment]
@anhdungpham I pulled in the new changes and it triggered for both create and update! However, I don't see the contacts in Salesforce (maybe i'm looking at the wrong page). 

Task for update: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-amanda/mesa/automations/629f7c9e8b20f9468859c780/queue/task/629f7d047a2fac2be10f7136

Task for create: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-amanda/mesa/automations/629f7c9e8b20f9468859c780/queue/task/629f7de5ea581072aa79b610

**Comment by amandahom** [comment]
@anhdungpham Yep. My bad, I was looking at the wrong thing. Thanks!

For Delighted, I am running into issues with the token: {{delighted_survey.person.email}}

It's empty when you try to search for customer so thats why my Customer Add Tag action is failing. 

Tried looking at the issue (by adding a bunch of activity logs) but couldn't figure it out: https://www.theshoppad.com/homeroom.theshoppad.com/admin/backdoor/shoppad-amanda/mesa/automations/629e6fdd2236a566a220b90f/queue/task/629f83ad7604fb211e4d154e
Screen Shot 2022-06-07 at 10 01 09 AM

Example response: https://app.delighted.com/docs/api/webhooks#example-request-body-for-a-survey-response-object

**Comment by amandahom** [comment]
@anhdungpham Ah, I see. It worked when I enabled the workflow first. 

Every workflow works great except the **Add customer's orders to order notes** template!

**Pull request merged**
