### PR TITLE
Google Analytics: Update templates

### PR DESCRIPTION
**Pull request by amandahom**
#### PR Review Checklist

Readme
- [ ] Are the install steps clear
- [ ] Do all of the links work

mesa.json
- [ ] Key: does it reflect the folder structure? For instance, if the folder for the template is `shopify/order/send_to_another_system`, the key should be the same. 
- [ ] Name: is it logical, proper-cased?
- [ ] Description: is it logical, end in period?
- [ ] Tags: Do they exist on getmesa.com/templates, proper-cased, logical?
- [ ] Source: lowercase
- [ ] Destination: lowercase
- [ ] Enabled: If no configuration necessary `true`, if there are ANY setup steps `false`
- [ ] Do the Input/Output names make sense? How about the keys?
- [ ] Are Storage, Secrets and scripts well-named

Template code
- [ ] Is code readable and well-commented?

QA
- [x] In the ShopPad repo, `git checkout mesa/google-analytics-update`
- [x] Checkout this branch in the mesa-templates repo

**Template: Track Shopify refunds in Google Analytics**
- [x] Install template
- [x] Set up a GA property if you haven't already: https://docs.getmesa.com/article/1287-google-analytics#configuring
- [x] Locate your Tracking ID and paste it into the **GA Create Transaction - Google Analytics ID** field.
- [x] Save/enable/logging/debug logging
- [x] `sp dev tunnel shoppad-apps`
- [x] From the Shopify Admin, navigate to an order that can be used to refund
- [x] Start a refund by clicking on **Refund** in the top right hand corner
- [x] Increase the quantity next to any of the products and click on the green Refund button
- [x] Head back to the template and check if it ran
- [x]  Check in the Google Analytics dashboard for the transaction. In your Google Analytics account, click on Conversions, then Ecommerce, and then Sales Performance in the left sidebar. Make sure that you view today's date (not selected by default) and change the # of results. Might take some time.
- [x] Check that each transaction field looks correct
- [x] Does the template work

**Template: Send Recharge renewal data to Google Analytics**
- [x] Login into dev-mesa2: https://partners.shopify.com/111585/stores/59177533485
- [x] Go to **[dev] Mesa** app
- [x] Install the template
- [x] Select the Recharge credential for the Recharge Trigger: **recharge_2**
- [x] Locate your Tracking ID and paste it into the **GA Create Transaction** - **Google Analytics ID** field and the Attach Items to Transaction step. (2 times)
- [x] Save/enable/enable logging/debug logging
- [x] Head over to Recharge subscription app
- [x] Click on **Subscriptions**: https://dev-mesa2-sp.admin.rechargeapps.com/merchant/subscriptions?page=1&limit=25
- [x] Locate the Subscription ID: 286743463. Click on the ID
- [x] Locate the order under **Upcoming Order**. Click on the **...** icon. 
- [x] `sp dev tunnel shoppad-apps`
- [x] Click on **Process Order**
Screen Shot 2022-09-30 at 9 41 35 AM
- [x] You should see the webhook appear in your ngrok tab. Copy the entire payload. dev-mesa2's webhooks in Mesa are currently not working
- [x] Head back to the template. Test the template with your copied payload
- [x] Check if it ran okay
- [x] Check in Google Analytics dashboard for the transaction. In your Google Analytics account, click on **Conversions**, then **Ecommerce**, and then **Sales Performance** in the left sidebar. Make sure that you view today's date (not selected by default) and change the # of results. Might take some time.
- [x] Check that each transaction field looks correct
- [x] Click on the Transaction ID and check that each product in the order displays with correct details
- [x] Does the template work

#### Deploy checklist
- [ ] Squash and merge PR
- [ ] Add template key to https://homeroom.theshoppad.com/admin/#/mesa-templates

### CODE REVIEW

**Comment by anhdungpham** [comment]
@amandahom 

Template: Track Shopify refunds in Google Analytics
- This template worked great! 🥳

Template: Send Recharge renewal data to Google Analytics
- I have not been able to get the details to show in Google Analytics. I have provided screenshots of the Activity and Logs tab below.
- Let me know if there is something I should do differently or provide more screenshots?

Screen Shot 2022-10-12 at 8 48 01 AM
Screen Shot 2022-10-12 at 8 48 48 AM
Screen Shot 2022-10-12 at 8 49 00 AM
Screen Shot 2022-10-12 at 8 49 12 AM

**Comment by anhdungpham** [comment]
@amandahom 

Template: Send Recharge renewal data to Google Analytics

- Got this template to work!
- However on the Google Analytics side, I was unable to find the Item Variation/Category field coming from the **Attach Items to Transaction** step. Am I looking in the incorrect spot?

Screen Shot 2022-10-12 at 4 51 09 PM

Screen Shot 2022-10-12 at 4 52 15 PM

Screen Shot 2022-10-12 at 4 52 35 PM

Screen Shot 2022-10-12 at 4 52 41 PM

**Comment by amandahom** [comment]
@anhdungpham Heya, I talked to Jeff about the GA stuff. He mentioned that since we’re using the example that they provide from the API doc, it’s fine to push the PR knowing this. Maybe there’s some kind of hidden report where you can see it somewhere”

Whenever you get some free time, could you look at the PR again and lmk if its QA’d? Thanks!

**Comment by anhdungpham** [comment]
@amandahom Alrighty, that sounds fine to me! QA'd and good to go! 🥳

**Pull request merged**
