### PR TITLE
Add template: Update Shopify inventory levels from a CSV file on an FTP server

### PR DESCRIPTION
**Pull request by anhdungpham**
#### Description
- [MESA Templates Asana Task](https://app.asana.com/0/1199933048569373/1205318761444956/f)

#### QA Checklist
- [ ] Go to your Shopify Admin
- [ ] Go to a product and add a few variants
- [ ] Add product SKUs to each variant and make sure they are unique
- [ ] Go to Google Sheets
- [x] Create a CSV file with headers. [You can start with this Google Sheets example](https://docs.google.com/spreadsheets/d/10p68X6HC2HXM157CQz5BPPsAtASQsfWIeGAy3XK5B68/edit?usp=sharing)
- [x] Make changes to the CSV file to match product SKUs from your store
- [ ] Feel free to adjust the numbers under the Inventory column
- [ ] Click File > Download > .csv
- [x] Rename the downloaded file to inventory.csv
- [ ] Open FileZilla
- [ ] Connect to our FTP server with the details listed under dev-mesa ftp (for testing) in 1PW
- [x] View the cs-test folder
- [x] Add the inventory.csv file to this folder
- [ ] Go to the MESA dashboard
- [ ] Compress the files and import this template
- [x] Go through the Template Setup. Do the question(s) make sense? Make sure you inputted cs-test/inventory.csv when asked for the file name
- [ ] Go to the Builder tab
- [x] View the FTP by MESA Fetch CSV File step and change the polling system to 1 min or 5 min. Default is 1 hour frequency
- [ ] Save changes
- [x] Check out the code snippet in the Custom Code step. Make sure the description makes sense and logic in code snippet makes sense
- [ ] Turn on the workflow
- [ ] Turn on Logging debug mode
- [ ] Save changes
- [ ] Wait for the polling system
- [x] Check that the workflow ran successfully
- [x] Check the messages in the Logs page make sense. Make sure that the "Response" message is displaying the product variant details
- [ ] Go to your Shopify Admin and view the product
- [x] Refresh and check that the inventory levels updated for the product variants
- [x] Does the template work

#### PR Review Checklist

mesa.json
- [ ] key: Use the slug provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] name: Use the name provided in the task of the [MESA Templates](https://app.asana.com/0/1199933048569373/list) list.
- [ ] version: Keep as is.
- [ ] description: Remove this since we rely on Prismic.
- [ ] seconds: Remove this since we rely on Prismic.
- [ ] enabled: Set to `false`
- [ ] setup: Set to `true` to add the template setup. Otherwise, keep `false` if template setup is not applicable. For Google Sheets templates, set to `custom` as mentioned in the [Authoring templates that support the setup wizard](https://github.com/shoppad/ShopPad/blob/master/pub-site/apps/mesa/docs/authoring-templates.md#custom-template-setup-fields) documentation.
- [ ] Do the Input/Output names make sense? How about the keys?

Template code (Custom Code, Transform)
- [ ] Is code readable and well-commented?

#### Deploy Checklist
- [ ] Squash and merge PR

### CODE REVIEW

**Comment by amandahom** [comment]
@anhdungpham Works great. Few things:
1. For the selected Location in the **Set Inventory Level** step, I ran into issues because my selected location was disabled. I think merchants will run into issues if they have several locations for different products or selected the wrong location. Will that be mentioned anywhere?
Screenshot 2023-08-24 at 10 49 57 AM
2. For the Custom Code step, I think we can remove the logging on line 47 so we don't clog up the Logs since it will appear  when the request is made. `Mesa.log.info("Response", response);`

**Comment by anhdungpham** [comment]
@amandahom Thanks for taking a look!

1. That is good to bring up! Taking a look at the blog article I am converting from, it looks like we only mention to select the right location: https://www.getmesa.com/blog/how-to-connect-ftp-inventory-feed-to-update-shopify-products/

Screenshot 2023-08-24 at 10 58 33 AM

It seems we could include a description that includes this text. I shall bring it up to Jen to get her thoughts.

2. I was thinking about this a lot. If a merchant only had Logging turned on, having this `Mesa.log.info` statement would be helpful in troubleshooting since it has the product variant details (i.e. Product Title, Product Variant Title, Product ID, Product Variant ID). We would skip having to ask the merchant to turn on Logging Debug Mode and then replay.

Do you still think we should remove the `Mesa.log.info` statement?

**Comment by amandahom** [comment]
@anhdungpham Sounds good! I meant you can keep the other logs, except this one: https://github.com/shoppad/mesa-templates/pull/491/files#diff-a1bd12c3a1efe25db42bfcbad1fdcc8981b066802eda6219e6d68984cf88326aR47

Line 47: `Mesa.log.info("Response", response);`
Since you will see the response regardless if Logging is enabled or disabled. Just to lessen the amount of logging.

I double checked that disabling logging will still show Mesa.log.infos: https://www.theshoppad.com/homeroom.theshoppad.com/admin/supertool/shoppad-amanda/mesa/automations/64e7a697c78c5b77f94b3ead/queue

**Comment by anhdungpham** [comment]
@amandahom I understood what you meant with your suggestion of removing the `Mesa.log.info("Response", response);` line of code. Thanks for explaining again.

I believe your settings may be caching. Could you please make sure you refresh and empty cache and hard reload before testing the workflow?

This is what I see on the Logs page when I only have Logging turned on.

Screenshot 2023-08-24 at 11 59 53 AM

Screenshot 2023-08-24 at 11 58 15 AM

Screenshot 2023-08-24 at 11 58 21 AM

**Comment by amandahom** [comment]
@anhdungpham I am still seeing both responses on my end after a Hard Reload + Empty Cache but its okay. We can leave it in.
Screenshot 2023-08-24 at 12 29 55 PM

**Pull request merged**
